<div class="<?php echo $this->class ?>" id="<?php echo $this->element->getId() . '-wrapper' ?>">

    <?php if (!$this->element->removeLabelDecorator): ?>
        <div class="inputLabel" id="<?php echo $this->element->getId() . '-label' ?>">
            <?php echo $this->formLabel($this->element->getName(), $this->element->getLabel());?>
        </div>
    <?php endif?>
    <div class="inputElement" id="<?php echo $this->element->getId() . '-element' ?>">
        <?php echo $this->{$this->element->helper}($this->element->getName(), $this->element->getValue(), $this->element->getAttribs()) ?>
    </div>
    <div class="captchaImage" id="<?php echo $this->element->getId() . '-captcha-sid' ?>">
        <img src="/bitrix/tools/captcha.php?captcha_sid=<?php echo $this->element->getCaptchaSid()?>"/>
        <input type="hidden" name="captcha_sid" value="<?php echo $this->element->getCaptchaSid()?>">
    </div>

    <?php if (count($this->element->getMessages())):?>
        <?php echo $this->formErrors($this->element->getMessages());?>
    <?php endif?>
    <div class="hint"><?php echo $this->element->getDescription() ?></div>
</div>
<div class="clear"></div>